### ISSUE TITLE
Email Templating Infrastructure

### ISSUE THREAD

**Issue by baybatu** [expercise/expercise#105]
We need an email templating mechanism for new email template producing. It would be to nice add improved email assertion that overlooks whitespaces.

**Comment by yigit-darcin** [comment]
mandrill / sendgrid ? or velocity / freemarker ?

**Comment by ufukuzun** [comment]
Thymeleaf

**Comment by baybatu** [comment]
Also we still use sendgrid as email sender service.

**Comment by yigit-darcin** [comment]
thymeleaf ? :-1:

**Comment by baybatu** [comment]
Thymeleaf has natural templating that allows emails to be designed by non-developer person in future easily without dealing with template language constructs.
