### ISSUE TITLE
Improvement For Theme Listing Page

### ISSUE THREAD

**Issue by baybatu** [expercise/expercise#86]
It would be nice to have different design for each theme box. We may choose different color for each theme.

**Comment by baybatu** [comment]
We now show off a little tooltip for description of the theme.

**Comment by ufukuzun** [comment]
![screenshot from 2015-06-11 00 56 38](https://cloud.githubusercontent.com/assets/327434/8095193/05ebb4b6-0fd5-11e5-944c-a88451863c21.png)
